spkr_protection: Include missing unistd and pthread headers
The build was complaining about an implicit function declaration

hardware/qcom/audio/hal/audio_extn/spkr_protection.c:208:9: error: implicit declaration of function 'ioctl' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    if (ioctl(cal_fd, AUDIO_GET_CALIBRATION, &cal_data)) {
hardware/qcom/audio/hal/audio_extn/spkr_protection.c:151:13: error: implicit declaration of function 'pthread_mutex_lock' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            pthread_mutex_lock(&handle.mutex_spkr_prot);

And so on...

Signed-off-by: Daniel Vásquez <danielgusvt@yahoo.com>